In [3]:
import numpy as np

In [4]:
print(f"Numpy version is: {np.__version__}")

Numpy version is: 2.2.6


---
## 1 · From Python data — `np.array()`

The most fundamental constructor. NumPy infers the dtype from your input.

In [5]:
# 1-D array
a1 = np.array([10,20,30,40])
print(f"1D => {a1} \ntype => {a1.dtype} \nshape => {a1.shape}")

1D => [10 20 30 40] 
type => int64 
shape => (4,)


In [6]:
# 2-D array (nested list → matrix)
a2 = np.array([[1,3],[2,5]])
print(f"2D => {a2} \ntype => {a2.dtype} \nshape => {a2.shape}")

2D => [[1 3]
 [2 5]] 
type => int64 
shape => (2, 2)


In [7]:
a3 = np.array([[20,30],[50,20],[1,3]])
print(f"3D => {a3} \ntype => {a3.dtype} \nshape => {a3.shape}")

3D => [[20 30]
 [50 20]
 [ 1  3]] 
type => int64 
shape => (3, 2)


### Forcing a dtype

NumPy defaults to `int64` for integers and `float64` for floats.  
Use `dtype=` to override, critical for memory efficiency in ML.


In [8]:
a_f64 = np.array([1,2,3]) # 8 Bytes per element
a_f32 = np.array([4,5,6] , dtype= np.float32) # 4 Bytes per element
a_f16 = np.array([7,8,9] , dtype= np.float16)# 2 Bytes per element
a_i64 = np.array([400,500,600]) # 8 Bytes per element
a_i32 = np.array([800,900,300] , dtype=np.int32) # 4 Bytes per element
a_i16 = np.array([100,200,300] , dtype=np.int16) # 2 Bytes per element


In [38]:
print(f"float64 -> nbytes: {a_f64.nbytes} , ({a_f64.nbytes / len(a_f64)} byte per element)")
print(f"float32 -> nbytes: {a_f32.nbytes} , ({a_f32.nbytes / len(a_f32)} byte per element)")
print(f"float16 -> nbytes: {a_f16.nbytes} , ({a_f16.nbytes / len(a_f16)} byte per element)")
print(f"int64 -> nbytes : {a_i64.nbytes} , ({a_i64.nbytes / len(a_i64)} byte per element) ")
print(f"int32 -> nbytes : {a_i32.nbytes} , ({a_i32.nbytes / len(a_i32)} byte per element) ")
print(f"int16 -> nbytes : {a_i16.nbytes} , ({a_i16.nbytes / len(a_i16)} byte per element) ")

float64 -> nbytes: 24 , (8.0 byte per element)
float32 -> nbytes: 12 , (4.0 byte per element)
float16 -> nbytes: 6 , (2.0 byte per element)
int64 -> nbytes : 24 , (8.0 byte per element) 
int32 -> nbytes : 12 , (4.0 byte per element) 
int16 -> nbytes : 6 , (2.0 byte per element) 


---
## 2 · The ndarray anatomy — 7 attributes you must know


In [9]:
M = np.array([[1.0, 2.0, 3.0, 4.0],
              [5.0, 6.0, 7.0, 8.0],
              [9.0,10.0,11.0,12.0]])

print(f"ndim : {M.ndim}") # number of axes
print(f"shape : {M.shape}") # size along each axis
print(f"size : {M.size}") # total elements
print(f"dtype : {M.dtype}") # element type
print(f"itemsize : {M.itemsize}") # bytes per element
print(f"nbytes : {M.nbytes}") # total bytes 
print(f"strides : {M.strides}") # bytes to step along each axis

ndim : 2
shape : (3, 4)
size : 12
dtype : float64
itemsize : 8
nbytes : 96
strides : (32, 8)


- 32 (8 * 4 -> itemsize * number of elements in the column) : moving to the next column 
- 8 : moving to the next element

---
## 3 · dtype reference

| dtype | bits | typical use |
|-------|------|-------------|
| `int8` | 8 | tiny integers (-128 to 127) |
| `int32` | 32 | general integers |
| `int64` | 64 | default integer |
| `float16` | 16 | half precision (GPU, ML) |
| `float32` | 32 | ML model weights |
| `float64` | 64 | default float — science |
| `bool` | 8 | masks |
| `complex128` | 128 | signal processing |

### Casting between dtypes


In [ ]:
arr = np.array([1.9, 2.7, 3.1], dtype= np.float64)

#as_type : creates a brand-new copy of the array in memory and returns it
as_int = arr.astype(np.int32) # trancates toward zero
as_f32 = arr.astype(np.float32) #smaller foorprint
as_boll = arr.astype(np.bool) # 0 -> False , anything else True

print(f"float64 → int32 : {as_int}")
print(f"float64 → int32 : {as_f32}")
print(f"float64 → bool : {as_boll}")

# Check dtype limit
print(f"\nint16 limites : {np.iinfo(np.int16)}")
print(f"float32 limites : {np.finfo(np.float32)}")


float64 → int32 : [1 2 3]
float64 → int32 : [1.9 2.7 3.1]
float64 → bool : [ True  True  True]

int16 limites : Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

float32 limites : Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



---
## 4 · Range-based creation

### `np.arange` vs `np.linspace` — the most important distinction


In [29]:
# arange (start, stop, step) - stop is EXCLUSIVE
print(f"arange int : {np.arange(0, 10, 2)}") # [0 2 4 6 8]
print(f"arange float : {np.arange(0.0, 1.0, 0.25)}") # may give unexpected count!

# linspace(start, stop, num) - stop is INCLUSIVE 
print(f"linspace : {np.linspace(0, 1, 5)}")
print(f"linspace ex : {np.linspace(0, 1, 5 , endpoint= False)}")

#lofspace - 10^stop
print(f"logspace : {np.logspace(0, 3, 4)}")

arange int : [0 2 4 6 8]
arange float : [0.   0.25 0.5  0.75]
linspace : [0.   0.25 0.5  0.75 1.  ]
linspace ex : [0.  0.2 0.4 0.6 0.8]
logspace : [   1.   10.  100. 1000.]


> **Rule of thumb**: Use `arange` for integer sequences.  
> Use `linspace` whenever you need float steps or a specific count — float arithmetic in `arange` can silently produce the wrong number of elements.


---
## 5 · Pre-filled arrays


In [18]:
print(np.zeros((3, 4)))
print()
print(np.ones((2, 3) , dtype=int))
print()
print(np.full((3, 3) , 6.0))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 1 1]
 [1 1 1]]

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [19]:
# like variants - it could copy shape and dtype from an existing array
existing = np.array([[1, 2],[3, 4]])
print(f"\nzeros_like:\n {np.zeros_like(existing)}")
print(f"full_like(99):\n {np.full_like(existing , 99)}")



zeros_like:
 [[0 0]
 [0 0]]
full_like(99):
 [[99 99]
 [99 99]]


In [20]:
#empty -FASTEST but contains garbage
scratch = np.empty((1000 , 10000))
print(f"\nempty shape : {scratch}")


empty shape : [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


---
## 6 · Identity and diagonal matrices


In [23]:
# Identity matrix 
I4 = np.eye(4)
print("I4:\n" , I4)

#Off-diagonal identity
print(f"\neye(4, k=1) - superdiagonal:\n {np.eye(4, k=1)}")
print(f"eye(4, k=-1) - subdiagonal:\n {np.eye(4, k=-1)}")

# diag: extract diagonal form matrix, or build diagonal matrix from a vector
M = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(f"\ndiagonal of M: {np.diag(M)}")
print(f"diag matrix:\n {np.diag([10,20,30])}")

I4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

eye(4, k=1) - superdiagonal:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
eye(4, k=-1) - subdiagonal:
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

diagonal of M: [1 5 9]
diag matrix:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


---
## 7 · From functions — `np.fromfunction` and `np.indices`


In [25]:
# fromfunction(fn, shape) - fn receives index arrays
dist = np.fromfunction(lambda i, j: np.sqrt(i**2 + j**2) , (5,5))
print(f"Distance from origin:\n {np.round(dist, 2)}")

# indices - retruns index grids (useful for vectorised coordinate math)
rows, cols = np.indices((3, 4))
print(f"\nrow indices:\n {rows}")
print(f"col indices:\n {cols}")

Distance from origin:
 [[0.   1.   2.   3.   4.  ]
 [1.   1.41 2.24 3.16 4.12]
 [2.   2.24 2.83 3.61 4.47]
 [3.   3.16 3.61 4.24 5.  ]
 [4.   4.12 4.47 5.   5.66]]

row indices:
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
col indices:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


---
## 8 · Understanding memory — C-order vs F-order


In [27]:
M_c = np.array([[1, 2, 3],[4, 5, 6]] , order= 'C') # Row-major (default)
M_f = np.array([[1, 2, 3],[4, 5, 6]] , order= 'F') # Column-major

print(f"C strides {M_c.strides}")
print(f"F strides {M_f.strides}")

print(f"C contigious : {M_c.flags['C_CONTIGUOUS']}")
print(f"F contigious : {M_f.flags['F_CONTIGUOUS']}")

C strides (24, 8)
F strides (8, 16)
C contigious : True
F contigious : True


- order='C': [ 1, 2, 3, 4, 5, 6 ] (The first row finishes before the second begins)
- order='F': [ 1, 4, 2, 5, 3, 6 ] (The first column finishes before the second

In [28]:
# try with different shapes and sizes

---
## 9 · Summary cheatsheet

| Goal | Function |
|------|----------|
| From data | `np.array(list)` |
| N zeros | `np.zeros(shape)` |
| N ones | `np.ones(shape)` |
| Constant fill | `np.full(shape, val)` |
| Integer range | `np.arange(start, stop, step)` |
| Fixed count floats | `np.linspace(start, stop, num)` |
| Log scale | `np.logspace(start, stop, num)` |
| Identity | `np.eye(n)` |
| Diagonal | `np.diag(vector)` |
| Uninitialized | `np.empty(shape)` |

---

