# Exercise 02 — Indexing & Slicing

**numpy-mastery** · 10 problems · Easy → Hard

**Scope**: only concepts from `notebooks/02_indexing_slicing.ipynb`  
→ basic indexing, slicing (`start:stop:step`), 2-D indexing,  
→ fancy indexing, boolean masking, `np.where`, views vs copies

**Rules**:
- No loops unless explicitly allowed
- No broadcasting — that is Module 03
- Use `.copy()` wherever you need to avoid modifying the original

---


In [2]:
import numpy as np

---
### Problem 01 · Easy — 1-D slice
Given `arr`, extract the sub-array `[30, 40, 50, 60]`  
using a single slice (no fancy indexing).


In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

result01 = arr[2: 6]

In [4]:
assert result01.tolist() == [30, 40, 50, 60]
assert np.shares_memory(result01, arr), "Should be a view, not a copy"
print("✓ Problem 01 passed")


✓ Problem 01 passed


---
### Problem 02 · Easy — reverse and step
Given `arr`, produce `[80, 60, 40, 20]` in a single slice expression.  
(Every other element, reversed.)


In [5]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
# Soltion
result02 = arr[::-2]


In [6]:
assert result02.tolist() == [80, 60, 40, 20]
print("✓ Problem 02 passed")


✓ Problem 02 passed


---
### Problem 03 · Easy — 2-D row and column
Given matrix `M`, extract:
- `row1`: the entire second row as a 1-D array `[5, 6, 7, 8]`
- `col2`: the entire third column as a 1-D array `[3, 7, 11]`


In [7]:
M = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])
# Solution
row1 = M[1 , :]
col2 = M[: , 2]


In [21]:
assert row1.tolist() == [5, 6, 7, 8],  f"Got {row1.tolist()}"
assert col2.tolist() == [3, 7, 11],    f"Got {col2.tolist()}"
assert row1.ndim == 1
assert col2.ndim == 1
print("✓ Problem 03 passed")


✓ Problem 03 passed


---
### Problem 04 · Easy — sub-matrix
From `M`, extract the 2×2 centre block:
```
[[ 6,  7],
 [10, 11]]
```


In [14]:
M = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])
# Solution
centre = M[1:3 , 1:3]


In [15]:
assert centre.shape == (2, 2)
assert centre.tolist() == [[6, 7], [10, 11]], f"Got {centre.tolist()}"
print("✓ Problem 04 passed")


✓ Problem 04 passed


---
### Problem 05 · Easy — view vs copy
Demonstrate the view/copy distinction:
1. Create `view` as a slice of `original` (indices 2 to 5)
2. Create `copy` as an explicit copy of the same slice
3. Modify `view[0]` to `999`
4. Verify `original` changed but a fresh `original2[2:5].copy()` would not


In [18]:
original = np.array([10, 20, 30, 40, 50, 60, 70])
# Solution
view = original[2:5]
copy = original.copy()[2:5]
# modify view[0] = 999 here
view[0]= 999


In [19]:
assert view is not None and copy is not None
assert view[0] == 999,         "Set view[0] = 999"
assert original[2] == 999,     "original should have changed via view"
assert copy[0] != 999,         "copy should be independent"
assert np.shares_memory(view, original),   "view should share memory"
assert not np.shares_memory(copy, original), "copy should not share memory"
print("✓ Problem 05 passed")


✓ Problem 05 passed


---
### Problem 06 · Medium — checkerboard via slicing
Create an **8×8 checkerboard** of 0s and 1s (top-left = 0)  
using only `np.zeros` and two slice assignments. No loops.


In [27]:
# Solution
board = np.zeros((8,8))
board[1::2 , ::2] = 1
board[::2 , 1::2] = 1
board


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [28]:
assert board.shape == (8, 8)
for i in range(8):
    for j in range(8):
        assert board[i, j] == (i + j) % 2, f"Wrong at ({i},{j}): {board[i,j]}"
print("✓ Problem 06 passed")


✓ Problem 06 passed


---
### Problem 07 · Medium — border matrix via slicing
Create a **6×6 matrix** where border elements are `1` and interior is `0`.
Use `np.ones` and a single interior slice assignment. No loops.


In [36]:
# Solution
border = np.ones((6, 6))
border[1:5 , 1:5] = 0
border


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
assert border.shape == (6, 6)
# Check border
assert (border[0, :]  == 1).all()   # top row
assert (border[-1, :] == 1).all()   # bottom row
assert (border[:, 0]  == 1).all()   # left col
assert (border[:, -1] == 1).all()   # right col
# Check interior
assert (border[1:-1, 1:-1] == 0).all()
print("✓ Problem 07 passed")


✓ Problem 07 passed


---
### Problem 08 · Medium — boolean masking pipeline
Given `data`:
1. Extract all values **strictly between 0.3 and 0.7** into `filtered`
2. Count them into `count`
3. Compute their mean into `mean_val`
4. Replace all values **outside** [0.3, 0.7] with `0.0` in a new array `clipped`  
   (do not modify `data`)


In [ ]:
rng = np.random.default_rng(42)
data = rng.random(200)    # 200 values in [0, 1)

# YOUR CODE
filtered  = None
count     = None
mean_val  = None
clipped   = None


In [ ]:
assert filtered is not None
assert count == ((data > 0.3) & (data < 0.7)).sum()
assert np.isclose(mean_val, filtered.mean())
assert clipped.shape == data.shape
assert (clipped[(data <= 0.3) | (data >= 0.7)] == 0.0).all()
assert (clipped[(data > 0.3) & (data < 0.7)] == data[(data > 0.3) & (data < 0.7)]).all()
assert not np.shares_memory(clipped, data), "clipped must not modify data"
print(f"✓ Problem 08 passed — {count} values in range, mean={mean_val:.4f}")


---
### Problem 09 · Medium — fancy indexing
Given `scores` (shape `(6, 4)` — 6 students, 4 subjects):
1. Extract rows for students at indices `[0, 2, 5]` into `selected`
2. Extract the diagonal elements `[scores[0,0], scores[1,1], scores[2,2], scores[3,3]]`  
   into `diag` using fancy indexing (not `np.diag`)


In [49]:
rng = np.random.default_rng(7)
scores = rng.integers(50, 100, size=(6, 4))
print("scores:\n", scores)

# Solution
#diag = scores[[0],[0]]
selected = scores[[0, 2, 5]]
idx = np.array([0, 1, 2, 3])
diag = scores[idx, idx]


diag

scores:
 [[97 81 84 94]
 [78 88 91 61]
 [52 65 64 93]
 [95 50 74 91]
 [56 89 55 73]
 [90 65 67 63]]


array([97, 88, 64, 91])

In [50]:
assert selected.shape == (3, 4)
assert np.array_equal(selected, scores[[0, 2, 5]])

idx = np.array([0, 1, 2, 3])
expected_diag = scores[idx, idx]
assert np.array_equal(diag, expected_diag), f"Got {diag}, expected {expected_diag}"
print("✓ Problem 09 passed")


✓ Problem 09 passed


---
### Problem 10 · Hard — np.where + multi-condition masking
Given `signal` (1-D, 1000 elements), do all of the following **without loops**:
1. `relu` — apply ReLU: keep positives, replace negatives with `0.0`
2. `hard_tanh` — clamp to `[-1, 1]`: values below -1 become -1, above 1 become 1, rest unchanged  
   (use `np.where` or `np.clip`)
3. `sign_arr` — array of `+1`, `-1`, or `0` for each element's sign  
   (use `np.where`, not `np.sign`)
4. `n_pos`, `n_neg`, `n_zero` — count positives, negatives, and zeros  
   (use boolean masks `.sum()`)


In [55]:
rng = np.random.default_rng(0)
signal = rng.normal(0, 1.5, 1000)   # Gaussian, mean=0, std=1.5

# Solution
relu = np.where(signal < 0 ,0, signal )
hard_tanh = np.where(signal < -1 , -1, np.where(signal> 1, 1, signal ))
sign_arr  = np.where(signal > 0, 1, np.where(signal < 0, -1, 0))
n_pos  = (signal > 0).sum()
n_neg  = (signal < 0).sum()
n_zero = (signal == 0).sum()


In [56]:
assert relu is not None
# ReLU: no negatives, positives unchanged
assert (relu[signal <  0] == 0.0).all()
assert (relu[signal >= 0] == signal[signal >= 0]).all()

# hard_tanh
assert hard_tanh.min() >= -1.0
assert hard_tanh.max() <=  1.0
assert (hard_tanh[(-1 <= signal) & (signal <= 1)] ==
        signal[(-1 <= signal) & (signal <= 1)]).all()

# sign_arr must use only +1, -1, 0
assert set(np.unique(sign_arr)).issubset({-1, 0, 1})
assert (sign_arr[signal > 0] ==  1).all()
assert (sign_arr[signal < 0] == -1).all()
assert (sign_arr[signal == 0] == 0).all()

# counts must add up
assert n_pos + n_neg + n_zero == 1000
assert n_pos == (signal > 0).sum()
assert n_neg == (signal < 0).sum()
print(f"✓ Problem 10 passed — pos={n_pos}, neg={n_neg}, zero={n_zero}")


✓ Problem 10 passed — pos=466, neg=534, zero=0
