# Exercise 03 — Operations & Broadcasting

**numpy-mastery** · 10 problems · Easy → Hard

**Scope**: only concepts from `notebooks/03_operations_broadcasting.ipynb`  
→ element-wise arithmetic, comparisons, aggregation with `axis`, `keepdims`,  
→ the 3 broadcasting rules, in-place vs out-of-place operations

**Rules**:
- No loops unless explicitly allowed
- No `np.linalg`, no sorting, no `np.where` — those come later
- Use `axis=` deliberately — get the direction right

---


In [1]:
import numpy as np

---
### Problem 01 · Easy — element-wise arithmetic
Given two arrays `a` and `b` of the same shape, compute:
1. `total` — their element-wise sum
2. `diff` — their element-wise difference 
3. `ratio` — their element-wise division 


In [2]:
a = np.array([10.0, 20.0, 30.0, 40.0])
b = np.array([2.0, 4.0, 5.0, 8.0])

# YOUR CODE
total = a + b
diff  = a - b
ratio = a / b


In [3]:
assert total.tolist() == [12.0, 24.0, 35.0, 48.0]
assert diff.tolist()  == [8.0, 16.0, 25.0, 32.0]
assert ratio.tolist() == [5.0, 5.0, 6.0, 5.0]
print("✓ Problem 01 passed")


✓ Problem 01 passed


---
### Problem 02 · Easy — comparison → boolean array
Given `scores`, create `passed` — a boolean array that is `True` wherever
the score is `>= 60`, `False` otherwise. Then count how many passed into `n_passed`.


In [10]:
scores = np.array([45, 78, 60, 92, 55, 88, 59, 60])

# YOUR CODE
passed   = scores >= 60
n_passed = passed.sum()


In [11]:
assert passed.dtype == bool
assert passed.tolist() == [False, True, True, True, False, True, False, True]
assert n_passed == 5
print("✓ Problem 02 passed")


✓ Problem 02 passed


---
### Problem 03 · Easy — axis aggregation
Given `grades` (shape `(4, 3)` — 4 students, 3 exams):
1. `student_avg` — average score **per student** (one value per row) → shape `(4,)`
2. `exam_avg` — average score **per exam** (one value per column) → shape `(3,)`


In [14]:
grades = np.array([[80, 90, 70],
                    [60, 65, 70],
                    [95, 85, 100],
                    [50, 55, 60]])

# YOUR CODE
student_avg = grades.mean(axis = 1)
exam_avg    = grades.mean(axis = 0)


In [15]:
assert student_avg.shape == (4,)
assert np.allclose(student_avg, [80.0, 65.0, 93.333333, 55.0])
assert exam_avg.shape == (3,)
assert np.allclose(exam_avg, [71.25, 73.75, 75.0])
print("✓ Problem 03 passed")


✓ Problem 03 passed


---
### Problem 04 · Easy — keepdims
Given `M` (shape `(3, 4)`), compute the row-wise maximum **keeping the
collapsed dimension** so the result has shape `(3, 1)` instead of `(3,)`.


In [19]:
M = np.array([[3, 7, 2, 9],
              [1, 5, 8, 4],
              [6, 0, 3, 2]])

# YOUR CODE
row_max = M.max(axis = 1, keepdims = True)


In [20]:
assert row_max.shape == (3, 1)
assert row_max.tolist() == [[9], [8], [6]]
print("✓ Problem 04 passed")


✓ Problem 04 passed


---
### Problem 05 · Medium — broadcasting a row vector
Given `prices` (shape `(3, 4)` — 3 stores, 4 products) and `discount`
(shape `(4,)` — one discount rate per product), compute `final_prices`
where each product's price is reduced by its discount rate.

`final_prices[i, j] = prices[i, j] * (1 - discount[j])`


In [24]:
prices   = np.array([[100.0, 200.0, 50.0, 80.0],
                      [120.0, 180.0, 60.0, 90.0],
                      [110.0, 190.0, 55.0, 85.0]])
discount = np.array([0.1, 0.2, 0.0, 0.5])   # 10%, 20%, 0%, 50% off

# Solution
final_prices = prices * (1 - discount)


In [22]:
expected = prices * (1 - discount)
assert final_prices.shape == (3, 4)
assert np.allclose(final_prices, expected)
assert np.isclose(final_prices[0, 1], 160.0)   # 200 * 0.8
assert np.isclose(final_prices[1, 3], 45.0)    # 90 * 0.5
print("✓ Problem 05 passed")


✓ Problem 05 passed


---
### Problem 06 · Medium — broadcasting a column vector
Given `M` (shape `(4, 3)`), subtract the **row mean** from every element
in that row, so each row ends up with mean ≈ 0.

Hint: you'll need `axis=1` and `keepdims=True` together.


In [27]:
M = np.array([[10.0, 20.0, 30.0],
              [ 5.0,  5.0,  5.0],
              [ 1.0,  2.0,  3.0],
              [ 8.0,  6.0, 10.0]])

# Solution
M_centered = M - M.mean(axis =1, keepdims = True) 


In [26]:
assert M_centered.shape == M.shape
row_means_after = M_centered.mean(axis=1)
assert np.allclose(row_means_after, 0.0, atol=1e-10)
print("✓ Problem 06 passed")


✓ Problem 06 passed


---
### Problem 07 · Medium — outer sum via broadcasting
Without using `np.add.outer`, build a 6×6 matrix `outer_sum` where
`outer_sum[i, j] = i + j` (0-indexed), using only broadcasting  
(a `(6,1)` array plus a `(1,6)` array).


In [31]:
# YOUR CODE
outer_sum = np.arange(6)[: , None] + np.arange(6)[None ,:]
print(outer_sum)

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


In [32]:
assert outer_sum.shape == (6, 6)
expected = np.array([[i+j for j in range(6)] for i in range(6)])
assert np.array_equal(outer_sum, expected)
print("✓ Problem 07 passed")


✓ Problem 07 passed


---
### Problem 08 · Medium — broadcast_shapes sanity check
Without computing any actual array operation, use `np.broadcast_shapes`
to determine:
1. `shape_a` — the result shape of broadcasting `(5, 1, 3)` with `(1, 4, 1)`
2. `is_compatible` — a boolean: can `(3, 4)` broadcast with `(4, 5)`?
   (Hint: catch the `ValueError` to determine this.)


In [33]:
# YOUR CODE
shape_a = np.broadcast_shapes((5, 1, 3) ,(1, 4, 1) )

try:
    np.broadcast_shapes((3, 4), (4, 5))
    is_compatible = True
except ValueError as e:
    is_compatible = False



In [34]:
assert shape_a == (5, 4, 3)
assert is_compatible == False
print("✓ Problem 08 passed")


✓ Problem 08 passed


---
### Problem 09 · Hard — one-hot encoding via broadcasting
Given `labels` (shape `(6,)`, values in `0..3`) and `n_classes = 4`,
build `one_hot` of shape `(6, 4)` where `one_hot[i, j] = 1` if
`labels[i] == j`, else `0`. No loops — use broadcasting comparison.

Then verify every row sums to exactly 1.


In [35]:
labels = np.array([2, 0, 3, 1, 0, 2])
n_classes = 4

# YOUR CODE
one_hot = (labels[:, None] == np.arange(4)[None, :]).astype(int)


In [36]:
assert one_hot.shape == (6, 4)
expected = np.array([
    [0,0,1,0],
    [1,0,0,0],
    [0,0,0,1],
    [0,1,0,0],
    [1,0,0,0],
    [0,0,1,0],
])
assert np.array_equal(one_hot, expected)
assert (one_hot.sum(axis=1) == 1).all()
print("✓ Problem 09 passed")


✓ Problem 09 passed


---
### Problem 10 · Hard — z-score normalisation
Given `X` (shape `(100, 5)` — 100 samples, 5 features), normalise **each
column** to have mean 0 and standard deviation 1 (z-score normalisation):

`X_norm[:, j] = (X[:, j] - mean(X[:, j])) / std(X[:, j])`

No loops — pure broadcasting. Verify the result column-wise.


In [38]:
rng = np.random.default_rng(42)
X = rng.normal(loc=5.0, scale=2.0, size=(100, 5))

# Solution
X_norm = None


In [ ]:
assert X_norm.shape == X.shape
col_means = X_norm.mean(axis=0)
col_stds  = X_norm.std(axis=0)
assert np.allclose(col_means, 0.0, atol=1e-10)
assert np.allclose(col_stds, 1.0, atol=1e-10)
print("✓ Problem 10 passed")
print(f"  column means: {col_means}")
print(f"  column stds : {col_stds}")
