# Exercise 04 — Linear Algebra

**numpy-mastery** · 10 problems · Easy → Hard

**Scope**: only concepts from `notebooks/04_linear_algebra.ipynb`  
→ `@` / `np.matmul`, transpose, `LA.det`, `LA.inv`, `LA.matrix_rank`, `np.trace`,  
→ `LA.norm`, `LA.solve`, `LA.eig`, `LA.svd`

**Rules**:
- No loops
- No `np.random.default_rng` sampling beyond what's given in the setup —
  random distributions are Module 05
- Always prefer `LA.solve` over `LA.inv(A) @ b` where applicable

---


In [2]:
import numpy as np
from numpy import linalg as LA


---
### Problem 01 · Easy — element-wise vs matrix multiply
Given `A` and `B` (both `(2,2)`), compute:
1. `hadamard` — the element-wise product (`*`)
2. `matprod` — the matrix product (`@`)

They should be different!


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Solution
hadamard = A * B
matprod  = A @ B


In [5]:
assert hadamard.tolist() == [[2, 0], [3, 12]]
assert matprod.tolist()  == [[4, 6], [10, 12]]
assert not np.array_equal(hadamard, matprod)
print("✓ Problem 01 passed")


✓ Problem 01 passed


---
### Problem 02 · Easy — matrix-vector multiplication
Given matrix `M` (shape `(3, 4)`) and vector `v` (shape `(4,)`),
compute `result = M @ v`. What shape should `result` be?


In [8]:
M = np.array([[1, 0, 2, -1],
              [3, 1, 0,  2],
              [0, 2, 1,  1]])
v = np.array([1, 2, 1, 0])

# Solution
result = M @ v # (3, )


In [9]:
assert result.shape == (3,)
assert result.tolist() == [3, 5, 5]
print("✓ Problem 02 passed")


✓ Problem 02 passed


---
### Problem 03 · Easy — transpose and shape compatibility
Given `X` (shape `(5, 3)`), compute:
1. `gram` — `X.T @ X`, the Gram matrix (shape should be `(3, 3)`)
2. `cov_like` — `X @ X.T` (shape should be `(5, 5)`)


In [10]:
X = np.array([[1.0, 2.0, 0.0],
              [0.0, 1.0, 1.0],
              [2.0, 0.0, 1.0],
              [1.0, 1.0, 1.0],
              [0.0, 2.0, 0.0]])

# Solution
gram = X.T @ X
cov_like = X @ X.T


In [11]:
assert gram.shape == (3, 3)
assert cov_like.shape == (5, 5)
assert np.allclose(gram, X.T @ X)
assert np.allclose(cov_like, X @ X.T)
print("✓ Problem 03 passed")


✓ Problem 03 passed


---
### Problem 04 · Easy — determinant and invertibility
Given three matrices, determine which ones are invertible using `LA.det`.
Store `True`/`False` for each in `is_invertible_1/2/3`.


In [5]:
M1 = np.array([[2.0, 0.0], [0.0, 3.0]])     # diagonal, clearly invertible
M2 = np.array([[1.0, 2.0], [2.0, 4.0]])     # row2 = 2*row1, singular
M3 = np.array([[1.0, 2.0], [3.0, 5.0]])     # invertible

# Solution — use LA.det and check != 0
is_invertible_1 = True if LA.det(M1) != 0 else False 
is_invertible_2 = True if LA.det(M2) != 0 else False
is_invertible_3 = True if LA.det(M3) != 0 else False


In [6]:
assert is_invertible_1 == True
assert is_invertible_2 == False
assert is_invertible_3 == True
print("✓ Problem 04 passed")


✓ Problem 04 passed


---
### Problem 05 · Medium — verify the inverse
Given `A`, compute `A_inv` using `LA.inv`, then verify that
`A @ A_inv` is (approximately) the identity matrix.  
Store the boolean result in `is_identity`.


In [9]:
A = np.array([[4.0, 2.0],
              [7.0, 6.0]])

# Solution
A_inv = LA.inv(A)
is_identity = np.allclose(A @ A_inv, np.eye(2))


In [10]:
assert A_inv is not None
assert np.allclose(A @ A_inv, np.eye(2))
assert is_identity == True
print("✓ Problem 05 passed")


✓ Problem 05 passed


---
### Problem 06 · Medium — norms
Given vector `v`, compute:
1. `l2` — the L2 (Euclidean) norm
2. `l1` — the L1 (Manhattan) norm
3. `linf` — the L∞ (max absolute value) norm
4. `unit_v` — `v` normalised to have L2 norm exactly 1 (a unit vector)


In [11]:
v = np.array([3.0, -4.0, 0.0])

# Solution
l2 = LA.norm(v)             # sqrt(9+16+0) = 5.0
l1 = LA.norm(v, ord=1)      # |3|+|-4|+|0| = 7.0
linf = LA.norm(v, ord=np.inf) # max(3,4,0) = 4.0
unit_v = v / l2   # divide by its own L2 norm -> length becomes 1


In [12]:
assert np.isclose(l2, 5.0)
assert np.isclose(l1, 7.0)
assert np.isclose(linf, 4.0)
assert np.isclose(LA.norm(unit_v), 1.0)
assert np.allclose(unit_v, v / 5.0)
print("✓ Problem 06 passed")


✓ Problem 06 passed


---
### Problem 07 · Medium — solving a linear system
Solve the system:
```
2x +  y - z = 8
-3x - y + 2z = -11
-2x + y + 2z = -3
```
using `LA.solve` (NOT `LA.inv`). Store the solution vector as `solution`
where `solution = [x, y, z]`.


In [13]:
A = np.array([[2.0,  1.0, -1.0],
              [-3.0, -1.0, 2.0],
              [-2.0,  1.0, 2.0]])
b = np.array([8.0, -11.0, -3.0])

# Solution
solution = LA.solve(A, b)


In [14]:
assert solution is not None
assert np.allclose(A @ solution, b)
assert np.allclose(solution, [2.0, 3.0, -1.0])
print("✓ Problem 07 passed —", solution)


✓ Problem 07 passed — [ 2.  3. -1.]


---
### Problem 08 · Medium — eigenvalue verification
Given `A` and its eigendecomposition, verify the defining property
`A @ v = λ * v` for **every** eigenvector (not just the first).  
Store a single boolean `all_verified` that is `True` only if all checks pass.


In [15]:
A = np.array([[4.0, 1.0],
              [2.0, 3.0]])


# Solution
eigenvalues, eigenvectors = LA.eig(A)

all_verified = True
for i in range(len(eigenvalues)):
    v_i   = eigenvectors[:, i]
    lam_i = eigenvalues[i]
    if not np.allclose(A @ v_i, lam_i * v_i):
        all_verified = False



In [16]:
assert all_verified == True
print("✓ Problem 08 passed")
print("eigenvalues:", eigenvalues)


✓ Problem 08 passed
eigenvalues: [5. 2.]


---
### Problem 09 · Hard — SVD reconstruction and rank-1 approximation
Given matrix `M` (shape `(4, 3)`):
1. Compute the full SVD: `U, S, Vt`
2. Reconstruct `M` fully and verify it matches (`full_reconstruction`)
3. Build a **rank-1 approximation** using only the largest singular value
   (zero out all singular values except the first), store as `rank1_approx`
4. Compute the Frobenius norm of the reconstruction error for the rank-1
   approximation: `error = LA.norm(M - rank1_approx)`


In [17]:
M = np.array([[4.0, 0.0, 1.0],
              [2.0, 3.0, 0.0],
              [1.0, 1.0, 2.0],
              [0.0, 2.0, 1.0]])

# Solution
U, S, Vt = LA.svd(M, full_matrices=False)
full_reconstruction = U @ np.diag(S) @ Vt

# Keep only the largest singular value
S_rank1 = S.copy()
S_rank1[1:] = 0.0
rank1_approx = U @ np.diag(S_rank1) @ Vt

error = LA.norm(M - rank1_approx)

print("singular values:", S)
print("full reconstruction matches M:", np.allclose(M, full_reconstruction))
print("rank-1 approximation:\n", rank1_approx)
print(f"reconstruction error: {error:.4f}")


singular values: [5.26479762 3.11168128 1.89719414]
full reconstruction matches M: True
rank-1 approximation:
 [[2.84608654 1.77698571 1.11356282]
 [2.51024252 1.56729777 0.98216014]
 [1.55996144 0.97397923 0.61035216]
 [1.06291432 0.66364235 0.41587698]]
reconstruction error: 3.6444


In [18]:
assert U is not None
assert np.allclose(M, full_reconstruction, atol=1e-8)

assert S_rank1 is not None
assert (S_rank1[1:] == 0).all()
assert S_rank1[0] == S[0]

assert rank1_approx.shape == M.shape
assert error is not None
assert error > 0   # rank-1 approx is never exact for a rank>1 matrix
print(f"✓ Problem 09 passed — reconstruction error: {error:.4f}")


✓ Problem 09 passed — reconstruction error: 3.6444


---
### Problem 10 · Hard — polynomial regression via normal equation
Fit a **quadratic** model `y ≈ θ0 + θ1*x + θ2*x²` to the data below
using the normal equation `θ = (XᵀX)⁻¹Xᵀy` (solved via `LA.solve`).

1. Build the design matrix `X` with columns `[1, x, x²]`
2. Solve for `theta`
3. Compute `y_pred = X @ theta` and the R² score


In [19]:
# Data generated from y = 1 - 2x + 3x² + noise
x = np.array([-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0])
y = np.array([17.1, 11.0, 6.1, 2.4, 1.3, 0.9, 1.8, 4.9, 9.1])


# Solution
# Design matrix: columns [1, x, x^2]
X = np.column_stack([np.ones_like(x), x, x**2])

theta = LA.solve(X.T @ X, X.T @ y)
y_pred = X @ theta

ss_res = np.sum((y - y_pred) ** 2)
ss_tot = np.sum((y - y.mean()) ** 2)
r2 = 1 - ss_res / ss_tot

In [20]:
assert X.shape == (9, 3)
assert np.allclose(X[:, 0], 1.0)
assert np.allclose(X[:, 1], x)
assert np.allclose(X[:, 2], x**2)

assert theta is not None
assert np.allclose(theta, [1.0, -2.0, 3.0], atol=0.3), f"Got {theta}"

assert y_pred is not None
ss_res = np.sum((y - y_pred) ** 2)
ss_tot = np.sum((y - y.mean()) ** 2)
expected_r2 = 1 - ss_res / ss_tot
assert np.isclose(r2, expected_r2)
assert r2 > 0.95
print(f"✓ Problem 10 passed — θ={theta}, R²={r2:.4f}")


✓ Problem 10 passed — θ=[ 1.01904762 -2.01333333  3.02857143], R²=0.9986
